baseURL = "http://example.org/"
languageCode = "ru"
title = "My New Hugo Site"
theme = "default"

[menu]
  [[menu.main]]
    identifier = "main"
    name = "Главная"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "notes"
    name = "Заметки"
    url = "/notes/"
    weight = 100

[params]
  important = "Пример текста для блока с важной информацией"
